from __future__ import annotations

from ..shared import CelestialBodyId, DefinitionId, SpatialNodeId, StarSystemId, SurfaceCellId

STRUCTURAL_COMPONENTS = DefinitionId("base.resource.structural_components")
MACHINERY = DefinitionId("base.resource.machinery")
PRECISION_ELECTRONICS = DefinitionId("base.resource.precision_electronics")
BULK_STRUCTURE = DefinitionId("base.resource.bulk_structure")
FABRICATED_STRUCTURE = DefinitionId("base.resource.fabricated_structure")
BASIC_MACHINE_PARTS = DefinitionId("base.resource.basic_machine_parts")
CONSTRUCTION_EQUIPMENT = DefinitionId("base.resource.construction_equipment")
MINERAL_FEEDSTOCK = DefinitionId("base.resource.mineral_feedstock")
VOLATILE_BEARING_MATERIAL = DefinitionId("base.resource.volatile_bearing_material")
CERAMICS_GLASS = DefinitionId("base.resource.ceramics_glass")
PRECISION_COMPONENTS = DefinitionId("base.resource.precision_components")
METAL_FEEDSTOCK = DefinitionId("base.resource.metal_feedstock")
METAL_ORE = DefinitionId("base.resource.metal_ore")
WATER = DefinitionId("base.resource.water")
OXYGEN = DefinitionId("base.resource.oxygen")
HYDROGEN = DefinitionId("base.resource.hydrogen")
PROPELLANT = DefinitionId("base.resource.chemical_propellant")

# ---------------------------------------------------------------------------
# Spatial content. Surface geography is separate from player-operated
# Locations; orbital/non-surface nodes remain SpatialNodeDef endpoints.
# ---------------------------------------------------------------------------
SOL_SYSTEM = StarSystemId("base.star_system.sol")
EARTH_BODY = CelestialBodyId("base.body.earth")
MOON = CelestialBodyId("base.body.moon")

# Player-operated/pre-existing economic Locations. Baseline Content defines only
# Earth; lunar surface Locations are generated by Founding Deployment at runtime.
EARTH = SpatialNodeId("base.location.earth_industrial")

# Non-surface spatial nodes.
LEO = SpatialNodeId("base.node.low_earth_orbit")
LUNAR_ORBIT = SpatialNodeId("base.node.lunar_orbit")

# Surface Cell topology. Cell counts intentionally differ by body and the
# topology does not assume six neighbors.
EARTH_CELL_INDUSTRIAL = SurfaceCellId("base.cell.earth.industrial_core")
EARTH_CELL_COASTAL = SurfaceCellId("base.cell.earth.coastal")
EARTH_CELL_INLAND = SurfaceCellId("base.cell.earth.inland")

MOON_CELL_SOUTH_POLAR_RIDGE = SurfaceCellId("base.cell.moon.south_polar_ridge")
MOON_CELL_POLAR_COLD_TRAP = SurfaceCellId("base.cell.moon.polar_cold_trap")
MOON_CELL_SOUTH_POLAR_PLAIN = SurfaceCellId("base.cell.moon.south_polar_plain")
MOON_CELL_NEARSIDE_MARE = SurfaceCellId("base.cell.moon.nearside_mare")
MOON_CELL_EQUATORIAL_HIGHLANDS = SurfaceCellId("base.cell.moon.equatorial_highlands")
MOON_CELL_FARSIDE_HIGHLANDS = SurfaceCellId("base.cell.moon.farside_highlands")

# Geographic development / founding Content IDs.
SURFACE_CELL_DEVELOPMENT_PROJECT = DefinitionId("base.construction.surface_cell_development")
ROBOTIC_LUNAR_OUTPOST_FOUNDING_PACKAGE = DefinitionId("base.founding.robotic_lunar_outpost")

# ---------------------------------------------------------------------------
# Facilities. IDs and display names describe function, not placement.
# ---------------------------------------------------------------------------
EARTH_RESEARCH_LAB = DefinitionId("base.facility.research_laboratory")
EARTH_OBSERVATION_SATELLITE = DefinitionId("base.facility.earth_observation_satellite")
LUNAR_RESOURCE_SURVEY_ORBITER = DefinitionId("base.facility.lunar_resource_survey_orbiter")
MICROGRAVITY_EXPERIMENT_PLATFORM = DefinitionId("base.facility.microgravity_experiment_platform")
CREWED_ORBITAL_LABORATORY = DefinitionId("base.facility.crewed_orbital_laboratory")
ROBOTIC_GEOLOGY_STATION = DefinitionId("base.facility.robotic_geology_station")
SAMPLE_ANALYSIS_LABORATORY = DefinitionId("base.facility.sample_analysis_laboratory")
VACUUM_REGOLITH_PROCESS_LABORATORY = DefinitionId("base.facility.vacuum_regolith_process_laboratory")
GRID_POWER_SUPPLY = DefinitionId("base.facility.grid_power_supply")
ORBITAL_LOGISTICS_NODE = DefinitionId("base.facility.orbital_logistics_node")
EARTH_LAUNCH_SUPPORT = DefinitionId("base.facility.earth_launch_support")
VEHICLE_ASSEMBLY_FACILITY = DefinitionId("base.facility.vehicle_assembly")
ROBOTIC_SURVEY_PACKAGE = DefinitionId("base.facility.robotic_survey_package")
SURFACE_POWER_GRID = DefinitionId("base.facility.surface_solar_power_grid")
INDUSTRIAL_POWER_BLOCK = DefinitionId("base.facility.fission_power_unit")
CONSTRUCTION_YARD = DefinitionId("base.facility.construction_yard")
VOLATILE_EXTRACTOR = DefinitionId("base.facility.volatile_extractor")
VOLATILE_PROCESSING = DefinitionId("base.facility.volatile_processing")
VACUUM_MINERAL_HARVESTER = DefinitionId("base.facility.vacuum_mineral_harvester")
WATER_STORAGE = DefinitionId("base.facility.water_storage")
CRYOGENIC_STORAGE = DefinitionId("base.facility.cryogenic_storage")
BULK_STORAGE = DefinitionId("base.facility.bulk_stockpile")
CARGO_WAREHOUSE = DefinitionId("base.facility.cargo_warehouse")
SURFACE_DISTRIBUTION_HUB = DefinitionId("base.facility.surface_distribution_hub")
ELECTROLYSIS_PLANT = DefinitionId("base.facility.electrolysis")
PROPELLANT_PLANT = DefinitionId("base.facility.propellant_blending")
MINERAL_SINTERING = DefinitionId("base.facility.mineral_sintering")
ORE_PROCESSING = DefinitionId("base.facility.ore_processing")
METALLURGY = DefinitionId("base.facility.metallurgy")
FABRICATION_WORKSHOP = DefinitionId("base.facility.fabrication_workshop")
MACHINE_SHOP = DefinitionId("base.facility.machine_shop")
HEAVY_EQUIPMENT_ASSEMBLY = DefinitionId("base.facility.heavy_equipment_assembly")
MINERAL_QUARRY = DefinitionId("base.facility.mineral_quarry")
METAL_ORE_MINE = DefinitionId("base.facility.metal_ore_mine")
INDUSTRIAL_WATER_INTAKE = DefinitionId("base.facility.industrial_water_intake")
BASIC_STRUCTURAL_MATERIAL_PLANT = DefinitionId("base.facility.basic_structural_material_plant")
BASIC_MACHINERY_WORKS = DefinitionId("base.facility.basic_machinery_works")

# Industrial processes are separately selectable from facility definitions.
PROCESS_ELECTROLYSIS = DefinitionId("base.process.water_electrolysis")
PROCESS_PROPELLANT_BLEND = DefinitionId("base.process.propellant_blending")
PROCESS_MINERAL_SINTER = DefinitionId("base.process.mineral_sintering")
PROCESS_VOLATILE_WATER_RECOVERY = DefinitionId("base.process.volatile_water_recovery")
PROCESS_PRECISION_COMPONENTS = DefinitionId("base.process.precision_components")
PROCESS_STRUCTURAL_FABRICATION = DefinitionId("base.process.structural_fabrication")
PROCESS_ORE_PROCESS = DefinitionId("base.process.ore_processing")
PROCESS_METALLURGY = DefinitionId("base.process.metallurgy")
PROCESS_BASIC_MACHINING = DefinitionId("base.process.basic_machining")
PROCESS_HEAVY_EQUIPMENT = DefinitionId("base.process.heavy_equipment_assembly")
PROCESS_BASIC_STRUCTURAL_MATERIAL = DefinitionId("base.process.basic_structural_material")
PROCESS_BASIC_MACHINERY = DefinitionId("base.process.basic_machinery")

# Research DAG IDs are Content Definition IDs. Progression stage/category/series
# are metadata on ResearchDefinition, not implicit gates.
def research_id(code: str) -> DefinitionId:
    return DefinitionId(code)

RP_RESOURCE_CHAIN_01 = research_id("RP-RESOURCE-CHAIN-01")
RP_RESOURCE_CHAIN_02 = research_id("RP-RESOURCE-CHAIN-02")
RP_RESOURCE_CHAIN_03 = research_id("RP-RESOURCE-CHAIN-03")
RP_RESOURCE_CHAIN_04 = research_id("RP-RESOURCE-CHAIN-04")
RP_RESOURCE_CHAIN_05 = research_id("RP-RESOURCE-CHAIN-05")
RP_RESOURCE_CHAIN_06 = research_id("RP-RESOURCE-CHAIN-06")
RP_RESOURCE_CHAIN_12 = research_id("RP-RESOURCE-CHAIN-12")
RP_RESOURCE_CHAIN_13 = research_id("RP-RESOURCE-CHAIN-13")
MC_MANUFACTURING_CONSTRUCTION_01 = research_id("MC-MANUFACTURING-CONSTRUCTION-01")
MC_MANUFACTURING_CONSTRUCTION_05 = research_id("MC-MANUFACTURING-CONSTRUCTION-05")
MC_MANUFACTURING_CONSTRUCTION_09 = research_id("MC-MANUFACTURING-CONSTRUCTION-09")
MC_MANUFACTURING_CONSTRUCTION_10 = research_id("MC-MANUFACTURING-CONSTRUCTION-10")
SS_SENSING_01 = research_id("SS-SENSING-01")
SS_SENSING_04 = research_id("SS-SENSING-04")
SS_SENSING_05 = research_id("SS-SENSING-05")
LM_LOGISTICS_MAINTENANCE_01 = research_id("LM-LOGISTICS-MAINTENANCE-01")
CR_CRYOGENIC_STORAGE_TRANSFER_03 = research_id("CR-CRYOGENIC-STORAGE-TRANSFER-03")
CR_CRYOGENIC_STORAGE_TRANSFER_01 = research_id("CR-CRYOGENIC-STORAGE-TRANSFER-01")
CR_CRYOGENIC_STORAGE_TRANSFER_02 = research_id("CR-CRYOGENIC-STORAGE-TRANSFER-02")
PG_SOLAR_POWER_02 = research_id("PG-SOLAR-POWER-02")
FP_REACTOR_POWER_02 = research_id("FP-REACTOR-POWER-02")
CR_CRYOGENIC_STORAGE_TRANSFER_04 = research_id("CR-CRYOGENIC-STORAGE-TRANSFER-04")
BIO_HUMAN_BIOLOGY_MEDICINE_03 = research_id("BIO-HUMAN-BIOLOGY-MEDICINE-03")

# Operational Experience categories are Content-defined Knowledge dimensions.
EXPERIENCE_TRANSPORT_OPERATIONS = "base.experience.transport_operations"
EXPERIENCE_EXTRACTION_OPERATIONS = "base.experience.extraction_operations"
EXPERIENCE_MANUFACTURING_OPERATIONS = "base.experience.manufacturing_operations"

# Transport assets are reusable physical assets. Route eligibility is derived
# from performance and endpoint environment, not purpose/category labels.
REUSABLE_LAUNCH_VEHICLE = DefinitionId("base.vehicle.reusable_launch_vehicle")
REUSABLE_ORBITAL_CARGO_TUG = DefinitionId("base.vehicle.reusable_orbital_cargo_tug")
LUNAR_ORBITAL_SURVEY_SPACECRAFT = DefinitionId("base.vehicle.lunar_orbital_survey_spacecraft")
LUNAR_FLEET_SURVEY_PROVIDER = DefinitionId("base.survey_provider.lunar_orbital_spacecraft")
REUSABLE_SURFACE_CARGO_LANDER = DefinitionId("base.vehicle.reusable_surface_cargo_lander")
SURFACE_CARGO_HAULER = DefinitionId("base.vehicle.surface_cargo_hauler")


# Scientific Exploration campaigns are finite science activities, separate from resource survey.
CISLUNAR_SCIENCE_EXPLORATION = DefinitionId("base.scientific_exploration.cislunar_environment_observation")
