from __future__ import annotations

# Generated from the user-approved stage 1-4 implementation reference.
# The canonical design remains in docs; this file is Base Content data.
RESEARCH_DAG_ROWS = (
    ('CH-COMBUSTION-01', 1, 'chemical_propulsion', 'combustion', '液体推進剤噴射・混合比制御', ()),
    ('CH-COMBUSTION-02', 1, 'chemical_propulsion', 'combustion', '燃焼振動モード計測・抑制', ('CH-COMBUSTION-01',)),
    ('CH-COMBUSTION-03', 1, 'chemical_propulsion', 'combustion', '燃焼室壁面冷却流路設計', ('CH-COMBUSTION-02', 'MS-MATERIALS-01', 'TH-THERMAL-TRANSPORT-01')),
    ('CH-COMBUSTION-04', 2, 'chemical_propulsion', 'combustion', 'ターボポンプ吸込キャビテーション抑制', ('CH-COMBUSTION-03', 'MS-MATERIALS-01', 'CP-COMPUTING-RELIABILITY-01')),
    ('CH-COMBUSTION-05', 2, 'chemical_propulsion', 'combustion', '真空ノズル流れ剥離予測', ('CH-COMBUSTION-04',)),
    ('CH-COMBUSTION-06', 2, 'chemical_propulsion', 'combustion', '再着火時推進剤条件制御', ('CH-COMBUSTION-05', 'GN-NAVIGATION-01', 'CP-COMPUTING-RELIABILITY-02')),
    ('CH-COMBUSTION-07', 3, 'chemical_propulsion', 'combustion', '燃焼室壁面熱流束限界推定', ('CH-COMBUSTION-06', 'MS-MATERIALS-04', 'TH-THERMAL-TRANSPORT-03')),
    ('CH-COMBUSTION-08', 3, 'chemical_propulsion', 'combustion', '深度推力調整時燃焼安定保持', ('CH-COMBUSTION-07',)),
    ('CH-COMBUSTION-09', 3, 'chemical_propulsion', 'combustion', '燃焼器低サイクル熱疲労評価', ('CH-COMBUSTION-08', 'MS-MATERIALS-06', 'MC-MANUFACTURING-CONSTRUCTION-03')),
    ('CH-COMBUSTION-10', 4, 'chemical_propulsion', 'combustion', '反復熱サイクル寿命予測', ('CH-COMBUSTION-09', 'LM-LOGISTICS-MAINTENANCE-08')),
    ('CH-COMBUSTION-11', 4, 'chemical_propulsion', 'combustion', '再始動前熱状態推定・条件調整', ('CH-COMBUSTION-10', 'LM-LOGISTICS-MAINTENANCE-05', 'CP-COMPUTING-RELIABILITY-06')),
    ('CR-CRYOGENIC-STORAGE-TRANSFER-01', 1, 'cryogenic_propellant', 'cryogenic_storage_transfer', '極低温タンク支持部熱侵入評価', ()),
    ('CR-CRYOGENIC-STORAGE-TRANSFER-02', 1, 'cryogenic_propellant', 'cryogenic_storage_transfer', 'タンク加圧・推進剤供給圧制御', ('CR-CRYOGENIC-STORAGE-TRANSFER-01',)),
    ('CR-CRYOGENIC-STORAGE-TRANSFER-03', 2, 'cryogenic_propellant', 'cryogenic_storage_transfer', '微小重力下液面捕捉・気液分離', ('CR-CRYOGENIC-STORAGE-TRANSFER-02', 'GN-NAVIGATION-01')),
    ('CR-CRYOGENIC-STORAGE-TRANSFER-04', 2, 'cryogenic_propellant', 'cryogenic_storage_transfer', '極低温配管予冷・二相流遷移評価', ('CR-CRYOGENIC-STORAGE-TRANSFER-03', 'TH-THERMAL-TRANSPORT-03')),
    ('CR-CRYOGENIC-STORAGE-TRANSFER-05', 2, 'cryogenic_propellant', 'cryogenic_storage_transfer', '蒸発ガス生成率・タンク圧力予測', ('CR-CRYOGENIC-STORAGE-TRANSFER-04',)),
    ('CR-CRYOGENIC-STORAGE-TRANSFER-06', 3, 'cryogenic_propellant', 'cryogenic_storage_transfer', '毛細管式推進剤捕捉・供給', ('CR-CRYOGENIC-STORAGE-TRANSFER-05',)),
    ('CR-CRYOGENIC-STORAGE-TRANSFER-07', 3, 'cryogenic_propellant', 'cryogenic_storage_transfer', '能動冷却・蒸気再凝縮制御', ('CR-CRYOGENIC-STORAGE-TRANSFER-06', 'PD-STORAGE-DISTRIBUTION-06', 'TH-THERMAL-TRANSPORT-05')),
    ('CR-CRYOGENIC-STORAGE-TRANSFER-08', 3, 'cryogenic_propellant', 'cryogenic_storage_transfer', '微小重力下極低温流体移送', ('CR-CRYOGENIC-STORAGE-TRANSFER-07', 'LM-LOGISTICS-MAINTENANCE-03', 'CO-RF-COMMUNICATIONS-06')),
    ('CR-CRYOGENIC-STORAGE-TRANSFER-09', 4, 'cryogenic_propellant', 'cryogenic_storage_transfer', '無ベント充填時圧力平衡制御', ('CR-CRYOGENIC-STORAGE-TRANSFER-08', 'CP-COMPUTING-RELIABILITY-06', 'LM-LOGISTICS-MAINTENANCE-06')),
    ('CR-CRYOGENIC-STORAGE-TRANSFER-10', 4, 'cryogenic_propellant', 'cryogenic_storage_transfer', '反復充填時タンク熱履歴補償', ('CR-CRYOGENIC-STORAGE-TRANSFER-09',)),
    ('EP-PLASMA-THRUSTERS-01', 1, 'electric_propulsion', 'plasma_thrusters', '電気推進用プラズマ生成・電子源制御', ('PD-STORAGE-DISTRIBUTION-02',)),
    ('EP-PLASMA-THRUSTERS-02', 2, 'electric_propulsion', 'plasma_thrusters', 'ホール放電電位分布安定化', ('EP-PLASMA-THRUSTERS-01', 'PD-STORAGE-DISTRIBUTION-04')),
    ('EP-PLASMA-THRUSTERS-03', 2, 'electric_propulsion', 'plasma_thrusters', 'グリッド式イオン加速電極制御', ('EP-PLASMA-THRUSTERS-02',)),
    ('EP-PLASMA-THRUSTERS-04', 2, 'electric_propulsion', 'plasma_thrusters', '中和器電子放出安定化', ('EP-PLASMA-THRUSTERS-03',)),
    ('EP-PLASMA-THRUSTERS-05', 3, 'electric_propulsion', 'plasma_thrusters', '放電チャネル侵食率推定', ('EP-PLASMA-THRUSTERS-04', 'MS-MATERIALS-04', 'SS-SENSING-03')),
    ('EP-PLASMA-THRUSTERS-06', 3, 'electric_propulsion', 'plasma_thrusters', '推進器電力変動時プラズマ安定制御', ('EP-PLASMA-THRUSTERS-05', 'PD-STORAGE-DISTRIBUTION-06', 'TH-THERMAL-TRANSPORT-05')),
    ('EP-PLASMA-THRUSTERS-07', 3, 'electric_propulsion', 'plasma_thrusters', '長時間作動時推力校正', ('EP-PLASMA-THRUSTERS-06',)),
    ('EP-PLASMA-THRUSTERS-08', 4, 'electric_propulsion', 'plasma_thrusters', '多基ホールスラスタ同期運転', ('EP-PLASMA-THRUSTERS-07', 'CP-COMPUTING-RELIABILITY-07', 'PD-STORAGE-DISTRIBUTION-09')),
    ('EP-PLASMA-THRUSTERS-09', 4, 'electric_propulsion', 'plasma_thrusters', '多基イオン推進器ビーム干渉制御', ('EP-PLASMA-THRUSTERS-08',)),
    ('EP-PLASMA-THRUSTERS-10', 4, 'electric_propulsion', 'plasma_thrusters', '故障推進器分離・推力再配分', ('EP-PLASMA-THRUSTERS-09', 'AR-AUTONOMY-ROBOTICS-08')),
    ('FP-REACTOR-POWER-01', 2, 'fission_power', 'reactor_power', '核分裂炉反応度計測・制御', ('CP-COMPUTING-RELIABILITY-03', 'SS-SENSING-06')),
    ('FP-REACTOR-POWER-02', 2, 'fission_power', 'reactor_power', '原子炉中性子・温度計装耐放射線化', ('FP-REACTOR-POWER-01', 'MS-MATERIALS-07')),
    ('FP-REACTOR-POWER-03', 3, 'fission_power', 'reactor_power', '炉心熱除去・発電系熱結合制御', ('FP-REACTOR-POWER-02', 'TH-THERMAL-TRANSPORT-05', 'PD-STORAGE-DISTRIBUTION-06')),
    ('FP-REACTOR-POWER-04', 3, 'fission_power', 'reactor_power', '負荷変動時炉出力追従制御', ('FP-REACTOR-POWER-03', 'PD-STORAGE-DISTRIBUTION-07')),
    ('FP-REACTOR-POWER-05', 3, 'fission_power', 'reactor_power', '遮蔽配置・散乱線量推定', ('FP-REACTOR-POWER-04', 'HB-HABITATION-PROTECTION-04')),
    ('FP-REACTOR-POWER-06', 4, 'fission_power', 'reactor_power', '燃料燃焼度・反応度余裕推定', ('FP-REACTOR-POWER-05',)),
    ('FP-REACTOR-POWER-07', 4, 'fission_power', 'reactor_power', '停止後崩壊熱除去制御', ('FP-REACTOR-POWER-06', 'TH-THERMAL-TRANSPORT-07', 'AR-AUTONOMY-ROBOTICS-08')),
    ('FP-REACTOR-POWER-08', 4, 'fission_power', 'reactor_power', '炉出力・電力負荷協調制御', ('FP-REACTOR-POWER-07', 'PD-STORAGE-DISTRIBUTION-10')),
    ('NT-NUCLEAR-THERMAL-01', 2, 'nuclear_thermal_propulsion', 'nuclear_thermal', '高温核燃料・被覆材熱化学適合性', ('FP-REACTOR-POWER-01', 'MS-MATERIALS-04')),
    ('NT-NUCLEAR-THERMAL-02', 3, 'nuclear_thermal_propulsion', 'nuclear_thermal', '水素冷却炉心熱流動解析', ('NT-NUCLEAR-THERMAL-01', 'CR-CRYOGENIC-STORAGE-TRANSFER-07', 'TH-THERMAL-TRANSPORT-05', 'MS-MATERIALS-07')),
    ('NT-NUCLEAR-THERMAL-03', 3, 'nuclear_thermal_propulsion', 'nuclear_thermal', '炉心出口温度・圧力損失推定', ('NT-NUCLEAR-THERMAL-02',)),
    ('NT-NUCLEAR-THERMAL-04', 3, 'nuclear_thermal_propulsion', 'nuclear_thermal', '推進ノズル・炉心流量整合制御', ('NT-NUCLEAR-THERMAL-03', 'CH-COMBUSTION-05', 'GN-NAVIGATION-06')),
    ('NT-NUCLEAR-THERMAL-05', 4, 'nuclear_thermal_propulsion', 'nuclear_thermal', '燃料体熱流束限界・局所過熱推定', ('NT-NUCLEAR-THERMAL-04', 'MS-MATERIALS-10', 'FP-REACTOR-POWER-06')),
    ('NT-NUCLEAR-THERMAL-06', 4, 'nuclear_thermal_propulsion', 'nuclear_thermal', '再始動時炉心熱状態推定', ('NT-NUCLEAR-THERMAL-05', 'LM-LOGISTICS-MAINTENANCE-08', 'CP-COMPUTING-RELIABILITY-06')),
    ('NT-NUCLEAR-THERMAL-07', 4, 'nuclear_thermal_propulsion', 'nuclear_thermal', '停止後残留熱・水素パージ制御', ('NT-NUCLEAR-THERMAL-06', 'TH-THERMAL-TRANSPORT-07')),
    ('PG-SOLAR-POWER-01', 1, 'power_generation', 'solar_power', '宇宙放射線下太陽電池劣化評価', ()),
    ('PG-SOLAR-POWER-02', 1, 'power_generation', 'solar_power', '展開式太陽電池面の姿勢保持', ('PG-SOLAR-POWER-01', 'MS-MATERIALS-03', 'GN-NAVIGATION-01')),
    ('PG-SOLAR-POWER-03', 2, 'power_generation', 'solar_power', '多接合太陽電池セル動作点制御', ('PG-SOLAR-POWER-02',)),
    ('PG-SOLAR-POWER-04', 2, 'power_generation', 'solar_power', '太陽追尾・部分陰影電力最適化', ('PG-SOLAR-POWER-03', 'CP-COMPUTING-RELIABILITY-01')),
    ('PG-SOLAR-POWER-05', 3, 'power_generation', 'solar_power', '薄膜発電面展開時構造振動抑制', ('PG-SOLAR-POWER-04', 'MC-MANUFACTURING-CONSTRUCTION-04')),
    ('PG-SOLAR-POWER-06', 3, 'power_generation', 'solar_power', 'セル列故障時バイパス再構成', ('PG-SOLAR-POWER-05', 'PD-STORAGE-DISTRIBUTION-05')),
    ('PG-SOLAR-POWER-07', 4, 'power_generation', 'solar_power', '発電面セグメント状態推定', ('PG-SOLAR-POWER-06',)),
    ('PG-SOLAR-POWER-08', 4, 'power_generation', 'solar_power', '発電面指向・負荷協調制御', ('PG-SOLAR-POWER-07', 'PD-STORAGE-DISTRIBUTION-10', 'AR-AUTONOMY-ROBOTICS-08')),
    ('PD-STORAGE-DISTRIBUTION-01', 1, 'power_storage_distribution', 'storage_distribution', '二次電池充電率・温度状態推定', ()),
    ('PD-STORAGE-DISTRIBUTION-02', 1, 'power_storage_distribution', 'storage_distribution', '直流電力変換・負荷安定化', ('PD-STORAGE-DISTRIBUTION-01', 'CP-COMPUTING-RELIABILITY-01')),
    ('PD-STORAGE-DISTRIBUTION-03', 2, 'power_storage_distribution', 'storage_distribution', '蓄電池サイクル劣化予測', ('PD-STORAGE-DISTRIBUTION-02',)),
    ('PD-STORAGE-DISTRIBUTION-04', 2, 'power_storage_distribution', 'storage_distribution', '真空高電圧絶縁・放電抑制', ('PD-STORAGE-DISTRIBUTION-03', 'MS-MATERIALS-01')),
    ('PD-STORAGE-DISTRIBUTION-05', 2, 'power_storage_distribution', 'storage_distribution', '負荷優先度に基づく電力遮断制御', ('PD-STORAGE-DISTRIBUTION-04', 'CP-COMPUTING-RELIABILITY-04')),
    ('PD-STORAGE-DISTRIBUTION-06', 3, 'power_storage_distribution', 'storage_distribution', '高電圧直流母線状態推定', ('PD-STORAGE-DISTRIBUTION-05', 'CO-RF-COMMUNICATIONS-06')),
    ('PD-STORAGE-DISTRIBUTION-07', 3, 'power_storage_distribution', 'storage_distribution', '電源切替時過渡電圧抑制', ('PD-STORAGE-DISTRIBUTION-06',)),
    ('PD-STORAGE-DISTRIBUTION-08', 3, 'power_storage_distribution', 'storage_distribution', '長時間蓄電用再生型燃料電池制御', ('PD-STORAGE-DISTRIBUTION-07',)),
    ('PD-STORAGE-DISTRIBUTION-09', 4, 'power_storage_distribution', 'storage_distribution', '故障区間選択遮断・再給電', ('PD-STORAGE-DISTRIBUTION-08', 'AR-AUTONOMY-ROBOTICS-08')),
    ('PD-STORAGE-DISTRIBUTION-10', 4, 'power_storage_distribution', 'storage_distribution', '分散電源電圧・電力協調', ('PD-STORAGE-DISTRIBUTION-09', 'CP-COMPUTING-RELIABILITY-08')),
    ('PD-STORAGE-DISTRIBUTION-11', 4, 'power_storage_distribution', 'storage_distribution', '設備間電力融通・負荷平準化', ('PD-STORAGE-DISTRIBUTION-10', 'CP-COMPUTING-RELIABILITY-09')),
    ('TH-THERMAL-TRANSPORT-01', 1, 'thermal_control', 'thermal_transport', '真空環境放射平衡・表面光学特性評価', ()),
    ('TH-THERMAL-TRANSPORT-02', 1, 'thermal_control', 'thermal_transport', '受動熱結合・断熱境界設計', ('TH-THERMAL-TRANSPORT-01',)),
    ('TH-THERMAL-TRANSPORT-03', 2, 'thermal_control', 'thermal_transport', 'ヒートパイプ毛細管限界評価', ('TH-THERMAL-TRANSPORT-02', 'MS-MATERIALS-02')),
    ('TH-THERMAL-TRANSPORT-04', 2, 'thermal_control', 'thermal_transport', '可変熱抵抗・温度帯切替制御', ('TH-THERMAL-TRANSPORT-03',)),
    ('TH-THERMAL-TRANSPORT-05', 3, 'thermal_control', 'thermal_transport', '二相流ポンプ式熱輸送安定化', ('TH-THERMAL-TRANSPORT-04', 'PD-STORAGE-DISTRIBUTION-04')),
    ('TH-THERMAL-TRANSPORT-06', 3, 'thermal_control', 'thermal_transport', '展開放熱面流体接続・漏洩監視', ('TH-THERMAL-TRANSPORT-05', 'MC-MANUFACTURING-CONSTRUCTION-04')),
    ('TH-THERMAL-TRANSPORT-07', 4, 'thermal_control', 'thermal_transport', '多ループ熱系統故障隔離', ('TH-THERMAL-TRANSPORT-06', 'AR-AUTONOMY-ROBOTICS-08')),
    ('TH-THERMAL-TRANSPORT-08', 4, 'thermal_control', 'thermal_transport', '設備間廃熱授受・温度帯整合', ('TH-THERMAL-TRANSPORT-07', 'PD-STORAGE-DISTRIBUTION-11')),
    ('MS-MATERIALS-01', 1, 'materials_structures', 'materials', '高温材料強度・酸化挙動評価', ()),
    ('MS-MATERIALS-02', 1, 'materials_structures', 'materials', '真空摩擦・摩耗係数評価', ('MS-MATERIALS-01',)),
    ('MS-MATERIALS-03', 1, 'materials_structures', 'materials', '軽量加圧殻応力・座屈解析', ('MS-MATERIALS-02',)),
    ('MS-MATERIALS-04', 2, 'materials_structures', 'materials', '耐酸化表面被覆・界面劣化評価', ('MS-MATERIALS-03',)),
    ('MS-MATERIALS-05', 2, 'materials_structures', 'materials', '固体潤滑被膜摩耗寿命評価', ('MS-MATERIALS-04',)),
    ('MS-MATERIALS-06', 2, 'materials_structures', 'materials', '熱サイクル下加圧構造疲労評価', ('MS-MATERIALS-05',)),
    ('MS-MATERIALS-07', 2, 'materials_structures', 'materials', '放射線照射下材料脆化評価', ('MS-MATERIALS-06', 'SS-SENSING-06')),
    ('MS-MATERIALS-08', 3, 'materials_structures', 'materials', '粉塵混入下摺動部摩耗評価', ('MS-MATERIALS-07',)),
    ('MS-MATERIALS-09', 3, 'materials_structures', 'materials', '損傷許容加圧構造設計', ('MS-MATERIALS-08',)),
    ('MS-MATERIALS-10', 4, 'materials_structures', 'materials', '熱・照射複合負荷下材料寿命推定', ('MS-MATERIALS-09',)),
    ('MS-MATERIALS-11', 4, 'materials_structures', 'materials', '分散ひずみ計測による損傷位置推定', ('MS-MATERIALS-10', 'SS-SENSING-09')),
    ('MS-MATERIALS-12', 4, 'materials_structures', 'materials', '再製造材の機械特性ばらつき評価', ('MS-MATERIALS-11',)),
    ('MC-MANUFACTURING-CONSTRUCTION-01', 1, 'manufacturing_construction', 'manufacturing_construction', '真空環境機械式接合・締結荷重管理', ()),
    ('MC-MANUFACTURING-CONSTRUCTION-02', 2, 'manufacturing_construction', 'manufacturing_construction', '真空金属接合・接合部熱影響評価', ('MC-MANUFACTURING-CONSTRUCTION-01', 'MS-MATERIALS-01')),
    ('MC-MANUFACTURING-CONSTRUCTION-03', 2, 'manufacturing_construction', 'manufacturing_construction', '非破壊検査による接合欠陥検出', ('MC-MANUFACTURING-CONSTRUCTION-02', 'SS-SENSING-03')),
    ('MC-MANUFACTURING-CONSTRUCTION-04', 2, 'manufacturing_construction', 'manufacturing_construction', '構造部材相対位置・姿勢計測', ('MC-MANUFACTURING-CONSTRUCTION-03',)),
    ('MC-MANUFACTURING-CONSTRUCTION-05', 3, 'manufacturing_construction', 'manufacturing_construction', '軌道上接合工程の品質計測', ('MC-MANUFACTURING-CONSTRUCTION-04',)),
    ('MC-MANUFACTURING-CONSTRUCTION-06', 3, 'manufacturing_construction', 'manufacturing_construction', '低重力施工機械反力制御', ('MC-MANUFACTURING-CONSTRUCTION-05', 'AR-AUTONOMY-ROBOTICS-03')),
    ('MC-MANUFACTURING-CONSTRUCTION-07', 3, 'manufacturing_construction', 'manufacturing_construction', '粒状地盤支持力推定', ('MC-MANUFACTURING-CONSTRUCTION-06', 'RP-RESOURCE-CHAIN-02', 'SS-SENSING-04')),
    ('MC-MANUFACTURING-CONSTRUCTION-08', 3, 'manufacturing_construction', 'manufacturing_construction', '基礎形成・地盤締固め条件制御', ('MC-MANUFACTURING-CONSTRUCTION-07', 'SM-SURFACE-MOBILITY-06')),
    ('MC-MANUFACTURING-CONSTRUCTION-09', 4, 'manufacturing_construction', 'manufacturing_construction', '自動接合時寸法誤差補正', ('MC-MANUFACTURING-CONSTRUCTION-08', 'AR-AUTONOMY-ROBOTICS-07', 'CP-COMPUTING-RELIABILITY-06')),
    ('MC-MANUFACTURING-CONSTRUCTION-10', 4, 'manufacturing_construction', 'manufacturing_construction', '粉体原料焼結条件・強度相関', ('MC-MANUFACTURING-CONSTRUCTION-09', 'RP-RESOURCE-CHAIN-03', 'TH-THERMAL-TRANSPORT-05')),
    ('MC-MANUFACTURING-CONSTRUCTION-11', 4, 'manufacturing_construction', 'manufacturing_construction', '原料組成変動に対する成形条件補償', ('MC-MANUFACTURING-CONSTRUCTION-10', 'RP-RESOURCE-CHAIN-07')),
    ('MC-MANUFACTURING-CONSTRUCTION-12', 4, 'manufacturing_construction', 'manufacturing_construction', '複数施工機の作業域衝突回避', ('MC-MANUFACTURING-CONSTRUCTION-11', 'AR-AUTONOMY-ROBOTICS-09', 'CO-RF-COMMUNICATIONS-08')),
    ('MC-MANUFACTURING-CONSTRUCTION-13', 4, 'manufacturing_construction', 'manufacturing_construction', '構造健全性計測と補修位置決定', ('MC-MANUFACTURING-CONSTRUCTION-12', 'MS-MATERIALS-11', 'LM-LOGISTICS-MAINTENANCE-11')),
    ('CO-RF-COMMUNICATIONS-01', 1, 'communications', 'rf_communications', 'パケット化テレメトリ・コマンド変復調', ()),
    ('CO-RF-COMMUNICATIONS-02', 1, 'communications', 'rf_communications', 'コヒーレント測距・ドップラー計測', ('CO-RF-COMMUNICATIONS-01',)),
    ('CO-RF-COMMUNICATIONS-03', 2, 'communications', 'rf_communications', '高利得アンテナ指向誤差推定', ('CO-RF-COMMUNICATIONS-02', 'GN-NAVIGATION-01')),
    ('CO-RF-COMMUNICATIONS-04', 2, 'communications', 'rf_communications', '低S/N搬送波同期・復調', ('CO-RF-COMMUNICATIONS-03', 'CP-COMPUTING-RELIABILITY-03')),
    ('CO-RF-COMMUNICATIONS-05', 2, 'communications', 'rf_communications', '前方誤り訂正符号化・復号', ('CO-RF-COMMUNICATIONS-04',)),
    ('CO-RF-COMMUNICATIONS-06', 3, 'communications', 'rf_communications', '蓄積転送型通信セッション管理', ('CO-RF-COMMUNICATIONS-05', 'CP-COMPUTING-RELIABILITY-05')),
    ('CO-RF-COMMUNICATIONS-07', 3, 'communications', 'rf_communications', '遅延耐性メッセージ転送', ('CO-RF-COMMUNICATIONS-06', 'CP-COMPUTING-RELIABILITY-05')),
    ('CO-RF-COMMUNICATIONS-08', 4, 'communications', 'rf_communications', '時刻非同期多経路ルーティング', ('CO-RF-COMMUNICATIONS-07', 'CP-COMPUTING-RELIABILITY-07')),
    ('CO-RF-COMMUNICATIONS-09', 4, 'communications', 'rf_communications', '通信経路障害検出・自律迂回', ('CO-RF-COMMUNICATIONS-08', 'CP-COMPUTING-RELIABILITY-08')),
    ('CO-OPTICAL-COMMUNICATIONS-01', 2, 'communications', 'optical_communications', '光通信端末粗捕捉・視線安定化', ('GN-NAVIGATION-03',)),
    ('CO-OPTICAL-COMMUNICATIONS-02', 3, 'communications', 'optical_communications', '深宇宙光通信変復調・符号同期', ('CO-OPTICAL-COMMUNICATIONS-01', 'PD-STORAGE-DISTRIBUTION-06', 'CP-COMPUTING-RELIABILITY-05')),
    ('CO-OPTICAL-COMMUNICATIONS-03', 3, 'communications', 'optical_communications', '微小角追尾・機体ジッタ補償', ('CO-OPTICAL-COMMUNICATIONS-02', 'GN-NAVIGATION-06')),
    ('CO-OPTICAL-COMMUNICATIONS-04', 4, 'communications', 'optical_communications', '光通信端末自律捕捉・再捕捉', ('CO-OPTICAL-COMMUNICATIONS-03', 'AR-AUTONOMY-ROBOTICS-08')),
    ('CO-OPTICAL-COMMUNICATIONS-05', 4, 'communications', 'optical_communications', '光・電波リンク切替時セッション維持', ('CO-OPTICAL-COMMUNICATIONS-04',)),
    ('CP-COMPUTING-RELIABILITY-01', 1, 'onboard_computing', 'computing_reliability', 'リアルタイム制御計算・期限保証', ()),
    ('CP-COMPUTING-RELIABILITY-02', 1, 'onboard_computing', 'computing_reliability', 'ウォッチドッグ監視・安全状態遷移', ('CP-COMPUTING-RELIABILITY-01',)),
    ('CP-COMPUTING-RELIABILITY-03', 2, 'onboard_computing', 'computing_reliability', '耐放射線計算機エラー検出・訂正', ('CP-COMPUTING-RELIABILITY-02', 'MS-MATERIALS-07')),
    ('CP-COMPUTING-RELIABILITY-04', 2, 'onboard_computing', 'computing_reliability', '冗長計算結果照合・故障隔離', ('CP-COMPUTING-RELIABILITY-03',)),
    ('CP-COMPUTING-RELIABILITY-05', 3, 'onboard_computing', 'computing_reliability', 'オンボード時系列データ圧縮・優先送信', ('CP-COMPUTING-RELIABILITY-04', 'CO-RF-COMMUNICATIONS-05')),
    ('CP-COMPUTING-RELIABILITY-06', 3, 'onboard_computing', 'computing_reliability', '設備状態モデルによる劣化傾向推定', ('CP-COMPUTING-RELIABILITY-05', 'SS-SENSING-09')),
    ('CP-COMPUTING-RELIABILITY-07', 3, 'onboard_computing', 'computing_reliability', '分散計算ノード時刻同期', ('CP-COMPUTING-RELIABILITY-06',)),
    ('CP-COMPUTING-RELIABILITY-08', 4, 'onboard_computing', 'computing_reliability', '分散状態整合・ノード再参加制御', ('CP-COMPUTING-RELIABILITY-07', 'CO-RF-COMMUNICATIONS-08')),
    ('CP-COMPUTING-RELIABILITY-09', 4, 'onboard_computing', 'computing_reliability', '計算ノード故障時タスク再配置', ('CP-COMPUTING-RELIABILITY-08',)),
    ('CP-COMPUTING-RELIABILITY-10', 4, 'onboard_computing', 'computing_reliability', '通信断下データ整合・後同期', ('CP-COMPUTING-RELIABILITY-09',)),
    ('GN-NAVIGATION-01', 1, 'guidance_navigation_control', 'navigation', '慣性計測誤差推定・姿勢決定', ()),
    ('GN-NAVIGATION-02', 1, 'guidance_navigation_control', 'navigation', '軌道状態推定・地上測距融合', ('GN-NAVIGATION-01', 'CO-RF-COMMUNICATIONS-02')),
    ('GN-NAVIGATION-03', 1, 'guidance_navigation_control', 'navigation', '星姿勢計測・慣性航法統合', ('GN-NAVIGATION-02',)),
    ('GN-NAVIGATION-04', 1, 'guidance_navigation_control', 'navigation', '相対距離・相対姿勢状態推定', ('GN-NAVIGATION-03', 'SS-SENSING-01')),
    ('GN-NAVIGATION-05', 2, 'guidance_navigation_control', 'navigation', '地形相対位置推定', ('GN-NAVIGATION-04', 'SS-SENSING-01', 'CP-COMPUTING-RELIABILITY-03')),
    ('GN-NAVIGATION-06', 3, 'guidance_navigation_control', 'navigation', '惑星間航法誤差共分散推定', ('GN-NAVIGATION-05', 'CO-RF-COMMUNICATIONS-06')),
    ('GN-NAVIGATION-07', 3, 'guidance_navigation_control', 'navigation', '自動ランデブー接近軌道生成', ('GN-NAVIGATION-06', 'LM-LOGISTICS-MAINTENANCE-03')),
    ('GN-NAVIGATION-08', 3, 'guidance_navigation_control', 'navigation', '終端降下誘導・推力コマンド結合', ('GN-NAVIGATION-07',)),
    ('GN-NAVIGATION-09', 4, 'guidance_navigation_control', 'navigation', '相互測距による分散航法', ('GN-NAVIGATION-08', 'CO-RF-COMMUNICATIONS-08')),
    ('GN-NAVIGATION-10', 4, 'guidance_navigation_control', 'navigation', '非協力対象の相対運動推定', ('GN-NAVIGATION-09',)),
    ('GN-NAVIGATION-11', 4, 'guidance_navigation_control', 'navigation', '航法センサ故障時推定器再構成', ('GN-NAVIGATION-10', 'CP-COMPUTING-RELIABILITY-09')),
    ('GN-NAVIGATION-12', 4, 'guidance_navigation_control', 'navigation', '複数地点運航の到着時刻誤差管理', ('GN-NAVIGATION-11',)),
    ('AR-AUTONOMY-ROBOTICS-01', 1, 'autonomy_robotics', 'autonomy_robotics', '遠隔マニピュレータ位置・速度制御', ()),
    ('AR-AUTONOMY-ROBOTICS-02', 1, 'autonomy_robotics', 'autonomy_robotics', '条件分岐シーケンス実行・異常停止', ('AR-AUTONOMY-ROBOTICS-01',)),
    ('AR-AUTONOMY-ROBOTICS-03', 2, 'autonomy_robotics', 'autonomy_robotics', '力覚フィードバック作業制御', ('AR-AUTONOMY-ROBOTICS-02', 'SS-SENSING-01')),
    ('AR-AUTONOMY-ROBOTICS-04', 2, 'autonomy_robotics', 'autonomy_robotics', '故障検出・隔離・回復シーケンス', ('AR-AUTONOMY-ROBOTICS-03', 'CP-COMPUTING-RELIABILITY-04')),
    ('AR-AUTONOMY-ROBOTICS-05', 3, 'autonomy_robotics', 'autonomy_robotics', '長遅延通信下タスク再計画', ('AR-AUTONOMY-ROBOTICS-04', 'CO-RF-COMMUNICATIONS-07', 'CP-COMPUTING-RELIABILITY-06')),
    ('AR-AUTONOMY-ROBOTICS-06', 3, 'autonomy_robotics', 'autonomy_robotics', '複数機タスク割当・資源競合回避', ('AR-AUTONOMY-ROBOTICS-05', 'CO-RF-COMMUNICATIONS-07')),
    ('AR-AUTONOMY-ROBOTICS-07', 3, 'autonomy_robotics', 'autonomy_robotics', '作業対象認識・把持点推定', ('AR-AUTONOMY-ROBOTICS-06',)),
    ('AR-AUTONOMY-ROBOTICS-08', 4, 'autonomy_robotics', 'autonomy_robotics', '分散設備故障隔離・運転再構成', ('AR-AUTONOMY-ROBOTICS-07', 'CP-COMPUTING-RELIABILITY-08', 'CO-RF-COMMUNICATIONS-09')),
    ('AR-AUTONOMY-ROBOTICS-09', 4, 'autonomy_robotics', 'autonomy_robotics', '複数ロボット作業分担・進捗同期', ('AR-AUTONOMY-ROBOTICS-08',)),
    ('AR-AUTONOMY-ROBOTICS-10', 4, 'autonomy_robotics', 'autonomy_robotics', '無人作業中断・再開状態保存', ('AR-AUTONOMY-ROBOTICS-09',)),
    ('SS-SENSING-01', 1, 'sensing_science', 'sensing', '軌道光学撮像・姿勢同期', ()),
    ('SS-SENSING-02', 1, 'sensing_science', 'sensing', '表面分光反射率・組成推定', ('SS-SENSING-01',)),
    ('SS-SENSING-03', 1, 'sensing_science', 'sensing', '構造ひずみ・温度センシング', ('SS-SENSING-02',)),
    ('SS-SENSING-04', 2, 'sensing_science', 'sensing', '地中レーダー反射断面推定', ('SS-SENSING-03', 'CO-RF-COMMUNICATIONS-02')),
    ('SS-SENSING-05', 2, 'sensing_science', 'sensing', '試料元素・鉱物組成分析', ('SS-SENSING-04',)),
    ('SS-SENSING-06', 2, 'sensing_science', 'sensing', '局地放射線粒子種別計測', ('SS-SENSING-05',)),
    ('SS-SENSING-07', 3, 'sensing_science', 'sensing', '三次元地下構造逆解析', ('SS-SENSING-06', 'CP-COMPUTING-RELIABILITY-05')),
    ('SS-SENSING-08', 3, 'sensing_science', 'sensing', '工程中成分オンライン分析', ('SS-SENSING-07', 'RP-RESOURCE-CHAIN-03')),
    ('SS-SENSING-09', 3, 'sensing_science', 'sensing', '分散センサ時刻・座標整合', ('SS-SENSING-08', 'CO-RF-COMMUNICATIONS-07')),
    ('SS-SENSING-10', 4, 'sensing_science', 'sensing', 'センサ劣化ドリフト自己校正', ('SS-SENSING-09', 'CP-COMPUTING-RELIABILITY-08')),
    ('SS-SENSING-11', 4, 'sensing_science', 'sensing', '複数観測手段の不確実度統合', ('SS-SENSING-10',)),
    ('EDL-EDL-01', 1, 'entry_descent_landing', 'edl', '極超音速対流・放射加熱推定', ()),
    ('EDL-EDL-02', 1, 'entry_descent_landing', 'edl', 'アブレーション熱防護材損耗評価', ('EDL-EDL-01', 'MS-MATERIALS-01', 'SS-SENSING-03')),
    ('EDL-EDL-03', 1, 'entry_descent_landing', 'edl', '再突入姿勢・弾道係数推定', ('EDL-EDL-02', 'GN-NAVIGATION-01')),
    ('EDL-EDL-04', 2, 'entry_descent_landing', 'edl', '熱防護材損傷非破壊評価', ('EDL-EDL-03', 'MC-MANUFACTURING-CONSTRUCTION-03')),
    ('EDL-EDL-05', 2, 'entry_descent_landing', 'edl', '超音速減速時空力荷重推定', ('EDL-EDL-04',)),
    ('EDL-EDL-06', 2, 'entry_descent_landing', 'edl', '地形相対着陸地点識別', ('EDL-EDL-05', 'GN-NAVIGATION-05')),
    ('EDL-EDL-07', 3, 'entry_descent_landing', 'edl', '揚力利用突入誘導・到達域制御', ('EDL-EDL-06', 'GN-NAVIGATION-06', 'CP-COMPUTING-RELIABILITY-06')),
    ('EDL-EDL-08', 3, 'entry_descent_landing', 'edl', '終端降下推力・航法閉ループ制御', ('EDL-EDL-07', 'CH-COMBUSTION-06', 'GN-NAVIGATION-08')),
    ('EDL-EDL-09', 3, 'entry_descent_landing', 'edl', '着陸脚接地荷重・転倒余裕推定', ('EDL-EDL-08', 'MS-MATERIALS-09', 'SS-SENSING-09')),
    ('EDL-EDL-10', 4, 'entry_descent_landing', 'edl', '熱防護残存余裕・再使用可否推定', ('EDL-EDL-09', 'MS-MATERIALS-11')),
    ('EDL-EDL-11', 4, 'entry_descent_landing', 'edl', '降下手段切替時姿勢・速度連続制御', ('EDL-EDL-10', 'CP-COMPUTING-RELIABILITY-08')),
    ('EDL-EDL-12', 4, 'entry_descent_landing', 'edl', '降下系故障時誘導・推力再構成', ('EDL-EDL-11', 'AR-AUTONOMY-ROBOTICS-08', 'CH-COMBUSTION-11')),
    ('SM-SURFACE-MOBILITY-01', 1, 'surface_mobility', 'surface_mobility', '車輪・粒状地盤せん断力推定', ()),
    ('SM-SURFACE-MOBILITY-02', 1, 'surface_mobility', 'surface_mobility', 'サスペンション荷重・接地状態推定', ('SM-SURFACE-MOBILITY-01', 'SS-SENSING-03')),
    ('SM-SURFACE-MOBILITY-03', 2, 'surface_mobility', 'surface_mobility', '低支持力地盤スリップ率制御', ('SM-SURFACE-MOBILITY-02', 'GN-NAVIGATION-05')),
    ('SM-SURFACE-MOBILITY-04', 2, 'surface_mobility', 'surface_mobility', '視界外経路再計画・スタック回避', ('SM-SURFACE-MOBILITY-03', 'AR-AUTONOMY-ROBOTICS-04')),
    ('SM-SURFACE-MOBILITY-05', 2, 'surface_mobility', 'surface_mobility', '粉塵侵入下駆動部摩耗監視', ('SM-SURFACE-MOBILITY-04', 'MS-MATERIALS-05', 'LM-LOGISTICS-MAINTENANCE-05')),
    ('SM-SURFACE-MOBILITY-06', 3, 'surface_mobility', 'surface_mobility', '長距離走行熱・電力収支予測', ('SM-SURFACE-MOBILITY-05', 'PD-STORAGE-DISTRIBUTION-05', 'TH-THERMAL-TRANSPORT-04')),
    ('SM-SURFACE-MOBILITY-07', 3, 'surface_mobility', 'surface_mobility', '地形通過性オンライン再評価', ('SM-SURFACE-MOBILITY-06', 'SS-SENSING-07')),
    ('SM-SURFACE-MOBILITY-08', 4, 'surface_mobility', 'surface_mobility', '複数車両経路競合・隊列間隔制御', ('SM-SURFACE-MOBILITY-07', 'CO-RF-COMMUNICATIONS-08', 'AR-AUTONOMY-ROBOTICS-09')),
    ('SM-SURFACE-MOBILITY-09', 4, 'surface_mobility', 'surface_mobility', '走行中故障時牽引・退避計画', ('SM-SURFACE-MOBILITY-08', 'LM-LOGISTICS-MAINTENANCE-11')),
    ('RP-RESOURCE-CHAIN-01', 1, 'resource_processing', 'resource_chain', '表面試料粒度・鉱物相分類', ()),
    ('RP-RESOURCE-CHAIN-02', 2, 'resource_processing', 'resource_chain', '粒状物掘削抵抗・排土挙動推定', ('RP-RESOURCE-CHAIN-01', 'SM-SURFACE-MOBILITY-03')),
    ('RP-RESOURCE-CHAIN-03', 2, 'resource_processing', 'resource_chain', '粒度分離・ふるい分け条件制御', ('RP-RESOURCE-CHAIN-02',)),
    ('RP-RESOURCE-CHAIN-04', 2, 'resource_processing', 'resource_chain', '磁性・密度差による鉱物選別', ('RP-RESOURCE-CHAIN-03', 'SS-SENSING-05')),
    ('RP-RESOURCE-CHAIN-05', 3, 'resource_processing', 'resource_chain', '低重力掘削反力閉ループ制御', ('RP-RESOURCE-CHAIN-02', 'AR-AUTONOMY-ROBOTICS-03')),
    ('RP-RESOURCE-CHAIN-06', 3, 'resource_processing', 'resource_chain', '揮発性成分加熱脱離・捕集', ('RP-RESOURCE-CHAIN-03', 'TH-THERMAL-TRANSPORT-04', 'SS-SENSING-05')),
    ('RP-RESOURCE-CHAIN-07', 3, 'resource_processing', 'resource_chain', '選鉱品位オンライン推定', ('RP-RESOURCE-CHAIN-04', 'SS-SENSING-08')),
    ('RP-RESOURCE-CHAIN-08', 3, 'resource_processing', 'resource_chain', '粉粒体密閉搬送・詰まり検出', ('RP-RESOURCE-CHAIN-03', 'LM-LOGISTICS-MAINTENANCE-05')),
    ('RP-RESOURCE-CHAIN-09', 4, 'resource_processing', 'resource_chain', '連続掘削・排土・搬送流量協調', ('RP-RESOURCE-CHAIN-05', 'RP-RESOURCE-CHAIN-08', 'AR-AUTONOMY-ROBOTICS-09', 'SM-SURFACE-MOBILITY-08')),
    ('RP-RESOURCE-CHAIN-10', 4, 'resource_processing', 'resource_chain', '選鉱品質フィードバック制御', ('RP-RESOURCE-CHAIN-07', 'CP-COMPUTING-RELIABILITY-08')),
    ('RP-RESOURCE-CHAIN-11', 4, 'resource_processing', 'resource_chain', '揮発性成分連続抽出・凝縮条件制御', ('RP-RESOURCE-CHAIN-06', 'RP-RESOURCE-CHAIN-09', 'TH-THERMAL-TRANSPORT-08')),
    ('RP-RESOURCE-CHAIN-12', 4, 'resource_processing', 'resource_chain', '回収水電解・気液分離による酸素水素精製', ('RP-RESOURCE-CHAIN-11', 'PD-STORAGE-DISTRIBUTION-11', 'LS-ATMOSPHERE-WATER-WASTE-07')),
    ('RP-RESOURCE-CHAIN-13', 4, 'resource_processing', 'resource_chain', '酸化物還元反応温度・酸素分圧制御', ('RP-RESOURCE-CHAIN-10', 'TH-THERMAL-TRANSPORT-08', 'PD-STORAGE-DISTRIBUTION-11')),
    ('RP-RESOURCE-CHAIN-14', 4, 'resource_processing', 'resource_chain', '副生成物流分離・再投入条件管理', ('RP-RESOURCE-CHAIN-13', 'LM-LOGISTICS-MAINTENANCE-07')),
    ('RP-RESOURCE-CHAIN-15', 4, 'resource_processing', 'resource_chain', '原料組成変動に対する反応条件補償', ('RP-RESOURCE-CHAIN-10', 'RP-RESOURCE-CHAIN-13', 'SS-SENSING-10', 'CP-COMPUTING-RELIABILITY-08')),
    ('LM-LOGISTICS-MAINTENANCE-01', 1, 'logistics_maintenance', 'logistics_maintenance', '機械式ドッキング接触荷重・捕捉制御', ('GN-NAVIGATION-04',)),
    ('LM-LOGISTICS-MAINTENANCE-02', 1, 'logistics_maintenance', 'logistics_maintenance', '貨物固定・加速度荷重管理', ('LM-LOGISTICS-MAINTENANCE-01',)),
    ('LM-LOGISTICS-MAINTENANCE-03', 2, 'logistics_maintenance', 'logistics_maintenance', '相対状態推定連動接近・結合シーケンス制御', ('LM-LOGISTICS-MAINTENANCE-02', 'GN-NAVIGATION-04', 'AR-AUTONOMY-ROBOTICS-04')),
    ('LM-LOGISTICS-MAINTENANCE-04', 2, 'logistics_maintenance', 'logistics_maintenance', '貨物接続部機械規格・誤接続防止', ('LM-LOGISTICS-MAINTENANCE-03',)),
    ('LM-LOGISTICS-MAINTENANCE-05', 2, 'logistics_maintenance', 'logistics_maintenance', '設備状態監視・異常傾向検出', ('LM-LOGISTICS-MAINTENANCE-04', 'SS-SENSING-03')),
    ('LM-LOGISTICS-MAINTENANCE-06', 3, 'logistics_maintenance', 'logistics_maintenance', '流体接続部漏洩検出・遮断', ('LM-LOGISTICS-MAINTENANCE-05', 'CR-CRYOGENIC-STORAGE-TRANSFER-08')),
    ('LM-LOGISTICS-MAINTENANCE-07', 3, 'logistics_maintenance', 'logistics_maintenance', '電力・データ接続時インターフェース整合確認', ('LM-LOGISTICS-MAINTENANCE-06', 'PD-STORAGE-DISTRIBUTION-07', 'CO-RF-COMMUNICATIONS-07')),
    ('LM-LOGISTICS-MAINTENANCE-08', 3, 'logistics_maintenance', 'logistics_maintenance', '劣化傾向時系列推定・交換時期予測', ('LM-LOGISTICS-MAINTENANCE-07', 'CP-COMPUTING-RELIABILITY-06')),
    ('LM-LOGISTICS-MAINTENANCE-09', 3, 'logistics_maintenance', 'logistics_maintenance', '遠隔部品交換・締結確認', ('LM-LOGISTICS-MAINTENANCE-08', 'AR-AUTONOMY-ROBOTICS-07')),
    ('LM-LOGISTICS-MAINTENANCE-10', 4, 'logistics_maintenance', 'logistics_maintenance', '無人貨物移載時荷重・位置閉ループ制御', ('LM-LOGISTICS-MAINTENANCE-09', 'AR-AUTONOMY-ROBOTICS-09', 'GN-NAVIGATION-10')),
    ('LM-LOGISTICS-MAINTENANCE-11', 4, 'logistics_maintenance', 'logistics_maintenance', '故障設備切離し・交換後機能検証', ('LM-LOGISTICS-MAINTENANCE-10', 'CP-COMPUTING-RELIABILITY-09')),
    ('LM-LOGISTICS-MAINTENANCE-12', 4, 'logistics_maintenance', 'logistics_maintenance', '保守履歴に基づく点検間隔適応', ('LM-LOGISTICS-MAINTENANCE-11',)),
    ('LS-ATMOSPHERE-WATER-WASTE-01', 1, 'life_support', 'atmosphere_water_waste', '船内圧力・酸素分圧制御', ('PD-STORAGE-DISTRIBUTION-02', 'SS-SENSING-03')),
    ('LS-ATMOSPHERE-WATER-WASTE-02', 1, 'life_support', 'atmosphere_water_waste', '飲用水貯蔵・微生物汚染監視', ('LS-ATMOSPHERE-WATER-WASTE-01', 'SS-SENSING-03')),
    ('LS-ATMOSPHERE-WATER-WASTE-03', 2, 'life_support', 'atmosphere_water_waste', '再生式二酸化炭素吸着・脱着', ('LS-ATMOSPHERE-WATER-WASTE-02', 'TH-THERMAL-TRANSPORT-03')),
    ('LS-ATMOSPHERE-WATER-WASTE-04', 2, 'life_support', 'atmosphere_water_waste', '温湿度凝縮水回収', ('LS-ATMOSPHERE-WATER-WASTE-03', 'TH-THERMAL-TRANSPORT-03')),
    ('LS-ATMOSPHERE-WATER-WASTE-05', 2, 'life_support', 'atmosphere_water_waste', '生活排水多段濾過・吸着', ('LS-ATMOSPHERE-WATER-WASTE-04',)),
    ('LS-ATMOSPHERE-WATER-WASTE-06', 2, 'life_support', 'atmosphere_water_waste', '尿蒸留・揮発成分分離', ('LS-ATMOSPHERE-WATER-WASTE-05', 'TH-THERMAL-TRANSPORT-04')),
    ('LS-ATMOSPHERE-WATER-WASTE-07', 3, 'life_support', 'atmosphere_water_waste', '水電解酸素生成・再結合安全制御', ('LS-ATMOSPHERE-WATER-WASTE-06', 'PD-STORAGE-DISTRIBUTION-06', 'CP-COMPUTING-RELIABILITY-04')),
    ('LS-ATMOSPHERE-WATER-WASTE-08', 3, 'life_support', 'atmosphere_water_waste', '微量有害ガス連続除去', ('LS-ATMOSPHERE-WATER-WASTE-07', 'SS-SENSING-08')),
    ('LS-ATMOSPHERE-WATER-WASTE-09', 3, 'life_support', 'atmosphere_water_waste', '膜分離・蒸留統合水再生', ('LS-ATMOSPHERE-WATER-WASTE-08', 'TH-THERMAL-TRANSPORT-05')),
    ('LS-ATMOSPHERE-WATER-WASTE-10', 3, 'life_support', 'atmosphere_water_waste', '有機廃棄物酸化分解・無機塩回収', ('LS-ATMOSPHERE-WATER-WASTE-09', 'BIO-HUMAN-BIOLOGY-MEDICINE-09')),
    ('LS-ATMOSPHERE-WATER-WASTE-11', 4, 'life_support', 'atmosphere_water_waste', '閉ループ大気成分収支推定・制御', ('LS-ATMOSPHERE-WATER-WASTE-10', 'CP-COMPUTING-RELIABILITY-08', 'BIO-HUMAN-BIOLOGY-MEDICINE-09')),
    ('LS-ATMOSPHERE-WATER-WASTE-12', 4, 'life_support', 'atmosphere_water_waste', '水質オンライン監視・処理条件補償', ('LS-ATMOSPHERE-WATER-WASTE-11', 'SS-SENSING-10')),
    ('LS-ATMOSPHERE-WATER-WASTE-13', 4, 'life_support', 'atmosphere_water_waste', '高回収率水循環の濃縮廃液管理', ('LS-ATMOSPHERE-WATER-WASTE-12',)),
    ('LS-ATMOSPHERE-WATER-WASTE-14', 4, 'life_support', 'atmosphere_water_waste', '回収栄養塩組成・有害成分分離', ('LS-ATMOSPHERE-WATER-WASTE-13', 'PL-PLANT-FOOD-06')),
    ('LS-ATMOSPHERE-WATER-WASTE-15', 4, 'life_support', 'atmosphere_water_waste', '大気・水・廃棄物流の物質収支統合', ('LS-ATMOSPHERE-WATER-WASTE-14', 'PL-PLANT-FOOD-07', 'CP-COMPUTING-RELIABILITY-08')),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-01', 1, 'life_science_medicine', 'human_biology_medicine', '短期宇宙飛行生理パラメータ計測', ('SS-SENSING-03',)),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-02', 1, 'life_science_medicine', 'human_biology_medicine', '個人放射線線量・活動履歴対応付け', ('BIO-HUMAN-BIOLOGY-MEDICINE-01',)),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-03', 2, 'life_science_medicine', 'human_biology_medicine', '微小重力筋骨格変化定量化', ('BIO-HUMAN-BIOLOGY-MEDICINE-02',)),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-04', 2, 'life_science_medicine', 'human_biology_medicine', '循環器・前庭系適応応答解析', ('BIO-HUMAN-BIOLOGY-MEDICINE-03',)),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-05', 2, 'life_science_medicine', 'human_biology_medicine', '組織等価線量・臓器別被曝推定', ('BIO-HUMAN-BIOLOGY-MEDICINE-04', 'SS-SENSING-06')),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-06', 3, 'life_science_medicine', 'human_biology_medicine', '長期微小重力生理応答モデル', ('BIO-HUMAN-BIOLOGY-MEDICINE-05', 'CP-COMPUTING-RELIABILITY-05')),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-07', 3, 'life_science_medicine', 'human_biology_medicine', '運動負荷対策の生理効果評価', ('BIO-HUMAN-BIOLOGY-MEDICINE-06',)),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-08', 3, 'life_science_medicine', 'human_biology_medicine', '粒子種別・線量率別生物影響評価', ('BIO-HUMAN-BIOLOGY-MEDICINE-07', 'HB-HABITATION-PROTECTION-04')),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-09', 3, 'life_science_medicine', 'human_biology_medicine', '閉鎖環境微生物群動態監視', ('BIO-HUMAN-BIOLOGY-MEDICINE-08', 'LS-ATMOSPHERE-WATER-WASTE-03')),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-10', 4, 'life_science_medicine', 'human_biology_medicine', '部分重力長期適応モデル', ('BIO-HUMAN-BIOLOGY-MEDICINE-09', 'SS-SENSING-10')),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-11', 4, 'life_science_medicine', 'human_biology_medicine', '累積被曝健康リスク推定', ('BIO-HUMAN-BIOLOGY-MEDICINE-10', 'HB-HABITATION-PROTECTION-06')),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-12', 4, 'life_science_medicine', 'human_biology_medicine', '閉鎖環境感染リスク・病原性監視', ('BIO-HUMAN-BIOLOGY-MEDICINE-11', 'LS-ATMOSPHERE-WATER-WASTE-11')),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-13', 4, 'life_science_medicine', 'human_biology_medicine', '遠隔診断下の処置優先度判定', ('BIO-HUMAN-BIOLOGY-MEDICINE-12', 'CO-RF-COMMUNICATIONS-08')),
    ('BIO-HUMAN-BIOLOGY-MEDICINE-14', 4, 'life_science_medicine', 'human_biology_medicine', '長期隔離環境の睡眠・認知負荷評価', ('BIO-HUMAN-BIOLOGY-MEDICINE-13',)),
    ('PL-PLANT-FOOD-01', 2, 'food_plant_science', 'plant_food', '閉鎖環境発芽・初期生育条件評価', ('LS-ATMOSPHERE-WATER-WASTE-02',)),
    ('PL-PLANT-FOOD-02', 2, 'food_plant_science', 'plant_food', '光周期・光量子束に対する成長応答', ('PL-PLANT-FOOD-01', 'HB-HABITATION-PROTECTION-02')),
    ('PL-PLANT-FOOD-03', 2, 'food_plant_science', 'plant_food', '養液pH・電気伝導度制御', ('PL-PLANT-FOOD-02', 'LS-ATMOSPHERE-WATER-WASTE-05')),
    ('PL-PLANT-FOOD-04', 3, 'food_plant_science', 'plant_food', '低重力根圏水分・酸素移動評価', ('PL-PLANT-FOOD-03', 'SS-SENSING-08')),
    ('PL-PLANT-FOOD-05', 3, 'food_plant_science', 'plant_food', '二酸化炭素濃度・光合成応答制御', ('PL-PLANT-FOOD-04', 'LS-ATMOSPHERE-WATER-WASTE-03')),
    ('PL-PLANT-FOOD-06', 3, 'food_plant_science', 'plant_food', '回収栄養塩の養液再利用', ('PL-PLANT-FOOD-05', 'LS-ATMOSPHERE-WATER-WASTE-10')),
    ('PL-PLANT-FOOD-07', 4, 'food_plant_science', 'plant_food', '栽培系・大気系ガス収支結合モデル', ('PL-PLANT-FOOD-06', 'LS-ATMOSPHERE-WATER-WASTE-11', 'CP-COMPUTING-RELIABILITY-08')),
    ('PL-PLANT-FOOD-08', 4, 'food_plant_science', 'plant_food', '非可食部有機物の栄養塩回収', ('PL-PLANT-FOOD-07', 'LS-ATMOSPHERE-WATER-WASTE-14')),
    ('PL-PLANT-FOOD-09', 4, 'food_plant_science', 'plant_food', '病害兆候画像診断・隔離判断', ('PL-PLANT-FOOD-08', 'AR-AUTONOMY-ROBOTICS-07')),
    ('PL-PLANT-FOOD-10', 4, 'food_plant_science', 'plant_food', '作物別収量・資源投入収支予測', ('PL-PLANT-FOOD-09', 'CP-COMPUTING-RELIABILITY-08')),
    ('HB-HABITATION-PROTECTION-01', 1, 'habitation_protection', 'habitation_protection', '加圧居住区漏洩率計測・区画隔離', ('MS-MATERIALS-03', 'SS-SENSING-03')),
    ('HB-HABITATION-PROTECTION-02', 1, 'habitation_protection', 'habitation_protection', '船内温湿度・照明日周期制御', ('HB-HABITATION-PROTECTION-01', 'LS-ATMOSPHERE-WATER-WASTE-01')),
    ('HB-HABITATION-PROTECTION-03', 2, 'habitation_protection', 'habitation_protection', '居住区騒音・振動曝露評価', ('HB-HABITATION-PROTECTION-02', 'BIO-HUMAN-BIOLOGY-MEDICINE-01')),
    ('HB-HABITATION-PROTECTION-04', 2, 'habitation_protection', 'habitation_protection', '放射線遮蔽材面密度・二次粒子評価', ('HB-HABITATION-PROTECTION-03', 'BIO-HUMAN-BIOLOGY-MEDICINE-05', 'MS-MATERIALS-03')),
    ('HB-HABITATION-PROTECTION-05', 2, 'habitation_protection', 'habitation_protection', '火災煙粒子検出・区画排煙制御', ('HB-HABITATION-PROTECTION-04', 'AR-AUTONOMY-ROBOTICS-04')),
    ('HB-HABITATION-PROTECTION-06', 3, 'habitation_protection', 'habitation_protection', '水・物資配置を利用した局所遮蔽設計', ('HB-HABITATION-PROTECTION-05', 'RP-RESOURCE-CHAIN-07')),
    ('HB-HABITATION-PROTECTION-07', 3, 'habitation_protection', 'habitation_protection', '長期閉鎖環境の作業・休息配置評価', ('HB-HABITATION-PROTECTION-06', 'BIO-HUMAN-BIOLOGY-MEDICINE-06')),
    ('HB-HABITATION-PROTECTION-08', 3, 'habitation_protection', 'habitation_protection', '居住区微生物表面汚染監視', ('HB-HABITATION-PROTECTION-07', 'BIO-HUMAN-BIOLOGY-MEDICINE-09')),
    ('HB-HABITATION-PROTECTION-09', 4, 'habitation_protection', 'habitation_protection', '漏洩・火災時居住区再区画制御', ('HB-HABITATION-PROTECTION-08', 'AR-AUTONOMY-ROBOTICS-08', 'LS-ATMOSPHERE-WATER-WASTE-11')),
    ('HB-HABITATION-PROTECTION-10', 4, 'habitation_protection', 'habitation_protection', '放射線イベント時退避区画線量最小化', ('HB-HABITATION-PROTECTION-09', 'BIO-HUMAN-BIOLOGY-MEDICINE-11', 'SS-SENSING-10')),
    ('HB-HABITATION-PROTECTION-11', 4, 'habitation_protection', 'habitation_protection', '居住環境負荷に応じた照明・温熱適応制御', ('HB-HABITATION-PROTECTION-10', 'LS-ATMOSPHERE-WATER-WASTE-11', 'BIO-HUMAN-BIOLOGY-MEDICINE-14')),
    ('HB-HABITATION-PROTECTION-12', 4, 'habitation_protection', 'habitation_protection', '長期隔離時プライバシー・共同作業配置評価', ('HB-HABITATION-PROTECTION-11', 'LS-ATMOSPHERE-WATER-WASTE-15', 'PD-STORAGE-DISTRIBUTION-09')),
    ('HB-HABITATION-PROTECTION-13', 4, 'habitation_protection', 'habitation_protection', '環境制御故障時居住区負荷縮退計画', ('HB-HABITATION-PROTECTION-12', 'AR-AUTONOMY-ROBOTICS-08', 'LS-ATMOSPHERE-WATER-WASTE-15')),
)
